// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	channel "github.com/keweegen/notification/internal/channel"
	entity "github.com/keweegen/notification/internal/entity"
)

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// CreateChannel mocks base method.
func (m *MockUser) CreateChannel(ctx context.Context, channel *entity.UserChannel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChannel", ctx, channel)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateChannel indicates an expected call of CreateChannel.
func (mr *MockUserMockRecorder) CreateChannel(ctx, channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChannel", reflect.TypeOf((*MockUser)(nil).CreateChannel), ctx, channel)
}

// DestroyChannel mocks base method.
func (m *MockUser) DestroyChannel(ctx context.Context, channelID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DestroyChannel", ctx, channelID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DestroyChannel indicates an expected call of DestroyChannel.
func (mr *MockUserMockRecorder) DestroyChannel(ctx, channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DestroyChannel", reflect.TypeOf((*MockUser)(nil).DestroyChannel), ctx, channelID)
}

// Exists mocks base method.
func (m *MockUser) Exists(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockUserMockRecorder) Exists(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockUser)(nil).Exists), ctx, userID)
}

// FindByChannel mocks base method.
func (m *MockUser) FindByChannel(ctx context.Context, userID int64, channel channel.Channel) (*entity.UserChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByChannel", ctx, userID, channel)
	ret0, _ := ret[0].(*entity.UserChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByChannel indicates an expected call of FindByChannel.
func (mr *MockUserMockRecorder) FindByChannel(ctx, userID, channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByChannel", reflect.TypeOf((*MockUser)(nil).FindByChannel), ctx, userID, channel)
}

// FindChannel mocks base method.
func (m *MockUser) FindChannel(ctx context.Context, channelID int64) (*entity.UserChannel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindChannel", ctx, channelID)
	ret0, _ := ret[0].(*entity.UserChannel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindChannel indicates an expected call of FindChannel.
func (mr *MockUserMockRecorder) FindChannel(ctx, channelID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindChannel", reflect.TypeOf((*MockUser)(nil).FindChannel), ctx, channelID)
}

// FindChannelsByUser mocks base method.
func (m *MockUser) FindChannelsByUser(ctx context.Context, userID int64) (entity.UserChannels, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindChannelsByUser", ctx, userID)
	ret0, _ := ret[0].(entity.UserChannels)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindChannelsByUser indicates an expected call of FindChannelsByUser.
func (mr *MockUserMockRecorder) FindChannelsByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindChannelsByUser", reflect.TypeOf((*MockUser)(nil).FindChannelsByUser), ctx, userID)
}

// UpdateChannel mocks base method.
func (m *MockUser) UpdateChannel(ctx context.Context, channel *entity.UserChannel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateChannel", ctx, channel)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateChannel indicates an expected call of UpdateChannel.
func (mr *MockUserMockRecorder) UpdateChannel(ctx, channel interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateChannel", reflect.TypeOf((*MockUser)(nil).UpdateChannel), ctx, channel)
}
