// Code generated by "stringer -type=MessageTemplate"; DO NOT EDIT.

package messagetemplate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Receipt-1]
}

const _MessageTemplate_name = "Receipt"

var _MessageTemplate_index = [...]uint8{0, 7}

func (i MessageTemplate) String() string {
	i -= 1
	if i < 0 || i >= MessageTemplate(len(_MessageTemplate_index)-1) {
		return "MessageTemplate(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageTemplate_name[_MessageTemplate_index[i]:_MessageTemplate_index[i+1]]
}
