// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Message       string
	MessageStatus string
	UserChannel   string
}{
	Message:       "message",
	MessageStatus: "message_status",
	UserChannel:   "user_channel",
}
